# Tokenize

In [1]:
from inltk.inltk import tokenize

tokenize('ભારતનું વેપારી શહેર અહમદાબ છે' ,'gu')

['▁ભારત', 'નું', '▁વેપારી', '▁શહેર', '▁અહમદ', 'ા', 'બ', '▁છે']

# embedding_vectors

In [2]:

from inltk.inltk import get_embedding_vectors

vectors = get_embedding_vectors('ભારત', 'gu') # where text is string in <code-of-language>

vectors = get_embedding_vectors('ભારત', 'gu')
vectors[0].shape



C:\Users\Jaynam\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\Jaynam\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\Jaynam\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's

(400,)

In [3]:
get_embedding_vectors('ગુજરતનું વેપારી શહેર અહમદાબાદ છે','gu')


[array([ 0.347118,  1.171592,  0.142763, -0.205282, ..., -0.261747,  0.784016, -0.079566, -0.674316], dtype=float32),
 array([ 0.294719, -0.232754,  0.762709,  0.516815, ...,  0.199538,  0.522705, -0.125957, -0.178957], dtype=float32),
 array([ 0.148547,  0.269452, -0.747668,  0.51683 , ..., -1.158624, -0.731481,  0.237688, -0.130309], dtype=float32),
 array([ 0.423279, -0.15338 , -0.158934, -0.203958, ..., -1.034738, -0.693858, -0.604404, -0.713103], dtype=float32),
 array([-0.05125 ,  0.527498, -0.516204, -0.192058, ...,  0.238527, -0.412072, -0.66316 , -0.701545], dtype=float32),
 array([-0.173078, -0.171721,  0.613051, -0.178029, ..., -0.505455, -0.128927,  0.10973 , -0.111237], dtype=float32),
 array([-0.443394,  0.221306,  0.231344, -0.609785, ..., -0.534826,  0.059691,  0.613627, -0.701841], dtype=float32),
 array([-1.794312,  0.569014, -0.94193 , -0.18315 , ..., -0.819459, -0.437872, -0.466019, -0.429546], dtype=float32)]

In [4]:
vectors = get_embedding_vectors('ભારતનું વેપારી શહેર અહમદાબાદ છે','gu')


In [5]:
len(vectors)

7

# Predict Next ‘n’ words

In [6]:
from inltk.inltk import predict_next_words
predict_next_words('ભારતનું વેપારી શહેર અહમદાબાદ' , 8, 'gu') 

'ભારતનું વેપારી શહેર અહમદાબાદ શહેર, જે ભારતનાં પંજાબ રાજ્યના મુખ્ય શહેર'

# Remove foreign languages

In [7]:
from inltk.inltk import remove_foreign_languages

remove_foreign_languages('ભારતનું વેપારી શહેર અહમદાબાદ છે is are', 'gu')

['▁ભારત', 'નું', '▁વેપારી', '▁શહેર', '▁અહમદ', 'ાબાદ', '▁છે', '▁is', '▁are']

In [8]:
from inltk.inltk import get_sentence_similarity

get_sentence_similarity('ગુજરતનું વેપારી શહેર અહમદાબાદ છે', 'ભારતનું વેપારી શહેર અહમદાબાદ છે', 'gu')

C:\Users\Jaynam\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\Jaynam\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\Jaynam\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's

C:\Users\Jaynam\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\Jaynam\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\Jaynam\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's

0.9048681259155273