In [ ]:
#Task 1 - Lexicon
#Lexicon -> collection of words/Phrases + Information (POS; tense Definitions..)
#Lexicon has lexical entries -> each entry is Word/Phrase -> has a HeadWord(Lemma) + Information

from nltk.corpus import stopwords
stopwords.words

In [1]:
import nltk
entries = nltk.corpus.cmudict.entries()
len(entries)

133737

In [2]:
entries[:100]

[('a', ['AH0']),
 ('a.', ['EY1']),
 ('a', ['EY1']),
 ('a42128',
  ['EY1',
   'F',
   'AO1',
   'R',
   'T',
   'UW1',
   'W',
   'AH1',
   'N',
   'T',
   'UW1',
   'EY1',
   'T']),
 ('aaa', ['T', 'R', 'IH2', 'P', 'AH0', 'L', 'EY1']),
 ('aaberg', ['AA1', 'B', 'ER0', 'G']),
 ('aachen', ['AA1', 'K', 'AH0', 'N']),
 ('aachener', ['AA1', 'K', 'AH0', 'N', 'ER0']),
 ('aaker', ['AA1', 'K', 'ER0']),
 ('aalseth', ['AA1', 'L', 'S', 'EH0', 'TH']),
 ('aamodt', ['AA1', 'M', 'AH0', 'T']),
 ('aancor', ['AA1', 'N', 'K', 'AO2', 'R']),
 ('aardema', ['AA0', 'R', 'D', 'EH1', 'M', 'AH0']),
 ('aardvark', ['AA1', 'R', 'D', 'V', 'AA2', 'R', 'K']),
 ('aaron', ['EH1', 'R', 'AH0', 'N']),
 ("aaron's", ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aarons', ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aaronson', ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ('aaronson', ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ("aaronson's", ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z']),
 ("aaronson's", ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z'

In [3]:
from nltk.corpus import wordnet as wn
wn.synsets('motorcar')

[Synset('car.n.01')]

In [7]:
wn.synset('car.n.01').lemma_names()

['car', 'auto', 'automobile', 'machine', 'motorcar']

In [13]:
#Task 2 - Simple Text Classifier
def gender_features(word):
    return {'last_letter':word[-1]}
gender_features('obama')

{'last_letter': 'a'}

In [12]:
from nltk.corpus import names
labeled_names = ([(name, 'male') for name in names.words('male.txt')]+
[(name, 'female') for name in names.words('female.txt')])

In [15]:
import random
random.shuffle(labeled_names)

In [18]:
featuresets=[(gender_features(n),gender) for (n,gender) in labeled_names]

In [20]:
train_set, test_test = featuresets[500:],featuresets[:500]

In [21]:
import nltk
classifier = nltk.NaiveBayesClassifier.train(train_set)

In [29]:
classifier.classify(gender_features('Roshan'))

'male'

In [30]:
classifier.classify(gender_features('Abhishek'))

'male'

In [35]:
classifier.classify(gender_features('Jaynam'))

'male'

In [33]:
classifier.classify(gender_features('Harshal'))

'male'

In [36]:
print(nltk.classify.accuracy(classifier,test_test))

0.76


In [40]:
from sklearn. feature_extraction. text import CountVectorizer 
#from sklearn.feature_extraction. tert import Tfidfvectorizer

In [44]:
vect = CountVectorizer(binary = True)
corpus = ["Tessaract is good optical character recognition engine  ", "optical character recognition is significant "]
vect. fit(corpus)

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [45]:
vocab = vect.vocabulary_
for key in sorted(vocab.keys()):
    print("{}:{}".format(key, vocab[key]))

character:0
engine:1
good:2
is:3
optical:4
recognition:5
significant:6
tessaract:7


In [47]:
print(vect.transform(["This is a good optical illusion"]).toarray())

[[0 0 1 1 1 0 0 0]]


In [48]:
print(vect.transform(corpus).toarray())

[[1 1 1 1 1 1 0 1]
 [1 0 0 1 1 1 1 0]]


In [49]:
from sklearn.metrics.pairwise import cosine_similarity

In [50]:
similarity = cosine_similarity(vect.transform(["Google Cloud Vision is a character recognition engine"]).toarray(), vect.transform(["OCR is an optical character recognition engine"]).toarray())

In [51]:
print(similarity)

[[0.89442719]]
